manager:
  image:
    repository: europe-docker.pkg.dev/kyma-project/dev/eventing-auth-manager
    tag: PR-18
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
replicas: 1
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP

nodeSelector: {}

tolerations: []

affinity: {}
