// Code generated by mockery v2.25.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetTokenUrl provides a mock function with given fields: ctx
func (_m *Client) GetTokenUrl(ctx context.Context) (*string, error) {
	ret := _m.Called(ctx)

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTokenUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenUrl'
type Client_GetTokenUrl_Call struct {
	*mock.Call
}

// GetTokenUrl is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) GetTokenUrl(ctx interface{}) *Client_GetTokenUrl_Call {
	return &Client_GetTokenUrl_Call{Call: _e.mock.On("GetTokenUrl", ctx)}
}

func (_c *Client_GetTokenUrl_Call) Run(run func(ctx context.Context)) *Client_GetTokenUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_GetTokenUrl_Call) Return(_a0 *string, _a1 error) *Client_GetTokenUrl_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTokenUrl_Call) RunAndReturn(run func(context.Context) (*string, error)) *Client_GetTokenUrl_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
