apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eventing-auth-manager.fullname" . }}-leader-election-role
  labels:
    app.kubernetes.io/component: eventing-auth-manager.kyma-project.io
    app.kubernetes.io/created-by: eventing-auth-manager
    app.kubernetes.io/part-of: eventing-auth-manager
  {{- include "eventing-auth-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eventing-auth-manager.fullname" . }}-leader-election-rolebinding
  labels:
    app.kubernetes.io/component: eventing-auth-manager.kyma-project.io
    app.kubernetes.io/created-by: eventing-auth-manager
    app.kubernetes.io/part-of: eventing-auth-manager
  {{- include "eventing-auth-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "eventing-auth-manager.fullname" . }}-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "eventing-auth-manager.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'