apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eventing-auth-manager.fullname" . }}-manager-role
  labels:
    app.kubernetes.io/component: eventing-auth-manager.kyma-project.io
  {{- include "eventing-auth-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymas
  verbs:
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - eventingauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - eventingauths/finalizers
  verbs:
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - eventingauths/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eventing-auth-manager.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: eventing-auth-manager.kyma-project.io
    app.kubernetes.io/created-by: eventing-auth-manager
    app.kubernetes.io/part-of: eventing-auth-manager
  {{- include "eventing-auth-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "eventing-auth-manager.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "eventing-auth-manager.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'