apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventing-auth-manager.fullname" . }}-metrics-service
  labels:
    app.kubernetes.io/component: eventing-auth-manager.kyma-project.io
    app.kubernetes.io/created-by: eventing-auth-manager
    app.kubernetes.io/part-of: eventing-auth-manager
    control-plane: controller-manager
  {{- include "eventing-auth-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/component: eventing-auth-manager.kyma-project.io
    control-plane: controller-manager
  {{- include "eventing-auth-manager.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}